# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: screen-256color

  WINIT_X11_SCALE_FACTOR: "1.0"

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  position:
    x: 0
    y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Fullscreen

  # Window title
  #title: Alacritty

  # Window class (Linux/BSD only):
  #class:
  # Application instance name
  #instance: Alacritty
  # General application class
  #general: Alacritty

  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  #gtk_theme_variant: None

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Liga SFMono Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Liga SFMono Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Liga SFMono Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Liga SFMono Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false

# Colors (Nord)
#colors:
## Default colors
#primary:
#background: '0x2E3440'
#foreground: '0xD8DEE9'

## Normal colors
#normal:
#black:   '0x3B4252'
#red:     '0xBF616A'
#green:   '0xA3BE8C'
#yellow:  '0xEBCB8B'
#blue:    '0x81A1C1'
#magenta: '0xB48EAD'
#cyan:    '0x88C0D0'
#white:   '0xE5E9F0'

## Bright colors
#bright:
#black:   '0x4C566A'
#red:     '0xBF616A'
#green:   '0xA3BE8C'
#yellow:  '0xEBCB8B'
#blue:    '0x81A1C1'
#magenta: '0xB48EAD'
#cyan:    '0x8FBCBB'
#white:   '0xECEFF4'

# Base16 Tomorrow Night - alacritty color config
# Chris Kempson (http://chriskempson.com)
# colors:
#   # Default colors
#   primary:
#     background: '0x2d2d2d'
#     foreground: '0xcccccc'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x2d2d2d'
#     cursor: '0xcccccc'

#   # Normal colors
#   normal:
#     black:   '0x2d2d2d'
#     red:     '0xf2777a'
#     green:   '0x99cc99'
#     yellow:  '0xffcc66'
#     blue:    '0x6699cc'
#     magenta: '0xcc99cc'
#     cyan:    '0x66cccc'
#     white:   '0xcccccc'

#   # Bright colors
#   bright:
#     black:   '0x999999'
#     red:     '0xf99157'
#     green:   '0x393939'
#     yellow:  '0x515151'
#     blue:    '0xb4b7b4'
#     magenta: '0xe0e0e0'
#     cyan:    '0xa3685a'
#     white:   '0xffffff'

# Colors (Poimandres)
colors:
  # Default colors
  primary:
    background: "0x1b1e28"
    foreground: "0xa6accd"

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  search:
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    matches:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    focused_match:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    bar:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: CellForeground
    background: "0x303340"

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black: "0x1b1e28"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0x89ddff"
    magenta: "0xfcc5e9"
    cyan: "0xadd7ff"
    white: "0xffffff"

  # Bright colors
  bright:
    black: "0xa6accd"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0xadd7ff"
    magenta: "0xfae4fc"
    cyan: "0x89ddff"
    white: "0xffffff"

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#000000'
  #  red:     '#8c3336'
  #  green:   '#7a8530'
  #  yellow:  '#97822e'
  #  blue:    '#506d8f'
  #  magenta: '#80638e'
  #  cyan:    '#497e7a'
  #  white:   '#9a9a9a'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  indexed_colors: []
