[ui]
paginate = "never"
merge-editor = "weave"

[user]
name = "Brian Chen"
email = "brianchen8990@gmail.com"

[merge-tools.weave]
program = "weave-driver"
merge-args = ["$base", "$left", "$right", "-o", "$output", "-l", "$marker_length", "-p", "$path"]
merge-conflict-exit-codes = [1]
merge-tool-edits-conflict-markers = true
conflict-marker-style = "git"
