{
  lib,
  pkgs,
  isOmarchy,
  ...
}:

let
  shared = import ./shared.nix;
  ezaBase = "eza --group-directories-first --icons=auto";

  aliases = shared.aliases // {
    hms = "home-manager switch -b backup --flake ~/nixpkgs-config#omarchy";
    reload = "hms && source ~/.bashrc && mise install";

    # Omarchy defines ls/lsa/lt/lta but leaves these zsh-compatible names free.
    l = ezaBase;
    ll = "${ezaBase} -lh";
    la = "${ezaBase} -lha";
  };

  environment = ''
    ${shared.environment}

    # Flutter/Android
    export ANDROID_SDK="$HOME/Android/Sdk"
    export ANDROID_NDK_HOME="$ANDROID_SDK/ndk"
    export PATH="$ANDROID_SDK/platform-tools:$ANDROID_SDK/cmdline-tools/latest/bin:$PATH"
    export CHROME_EXECUTABLE="/usr/bin/chromium"
  '';

  renderAliases =
    values:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "alias ${name}=${lib.escapeShellArg value}") values
    );

  shellInit = pkgs.writeTextFile {
    name = "shared-shell-init";
    destination = "/etc/profile.d/shared-shell.sh";
    text = ''
      # Shared shell layer, generated by nixpkgs-config.
      # Sourced from ~/.bashrc by scripts/omarchy-bootstrap.sh.

      ${environment}

      ${renderAliases aliases}

      # Omarchy already initialises starship, zoxide, mise and fzf. direnv and
      # broot are the only additions needed here.
      if command -v direnv >/dev/null 2>&1; then
        eval "$(direnv hook bash)"
      fi
      if [ -r "$HOME/.config/broot/launcher/bash/br" ]; then
        . "$HOME/.config/broot/launcher/bash/br"
      fi

      # Ghostty starts herdr before this interactive shell initialises, so the
      # long-lived herdr server does not retain shell-only secrets.
      if command -v glab >/dev/null 2>&1; then
        NPM_TOKEN="$(glab config get token --host git.jotta.us 2>/dev/null)"
        export NPM_TOKEN
      fi
    '';
  };
in
lib.mkIf isOmarchy {
  home.packages = [ shellInit ];
}
